[cosmic-ray]
module-path = "."
timeout = 10.0
excluded-modules = [
  "**/tests/**",
  "**/tests.py",
  "**/migrations/**",
  "**/management/**",
  "manage.py",
  "**/mysite/**",
]
test-command = "python manage.py test --parallel"

[cosmic-ray.distributor]
name = "local"
