from rest_framework import serializers


class ProductListOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    title = serializers.CharField()
    description = serializers.CharField()
    category = serializers.CharField()
    price = serializers.FloatField()
    discount_percentage = serializers.FloatField()
    rating = serializers.FloatField()
    stock = serializers.IntegerField()
    tags = serializers.CharField()
    brand = serializers.CharField()
    sku = serializers.CharField()
    weight = serializers.IntegerField()
    width = serializers.FloatField()
    height = serializers.FloatField()
    depth = serializers.FloatField()
    warranty_information = serializers.CharField()
    shipping_information = serializers.CharField()
    availability_status = serializers.CharField()
    return_policy = serializers.CharField()
    minimum_order_quantity = serializers.IntegerField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    barcode = serializers.CharField()
    qr_code = serializers.CharField()
    thumbnail = serializers.URLField()


class ProductDetailOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    title = serializers.CharField()
    description = serializers.CharField()
    category = serializers.CharField()
    price = serializers.FloatField()
    discount_percentage = serializers.FloatField()
    rating = serializers.FloatField()
    stock = serializers.IntegerField()
    tags = serializers.CharField()
    brand = serializers.CharField()
    sku = serializers.CharField()
    weight = serializers.IntegerField()
    width = serializers.FloatField()
    height = serializers.FloatField()
    depth = serializers.FloatField()
    warranty_information = serializers.CharField()
    shipping_information = serializers.CharField()
    availability_status = serializers.CharField()
    return_policy = serializers.CharField()
    minimum_order_quantity = serializers.IntegerField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    barcode = serializers.CharField()
    qr_code = serializers.CharField()
    thumbnail = serializers.URLField()


class ProductSearchOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    title = serializers.CharField()
    description = serializers.CharField()
    category = serializers.CharField()
    price = serializers.FloatField()
    discount_percentage = serializers.FloatField()
    rating = serializers.FloatField()
    stock = serializers.IntegerField()
    tags = serializers.CharField()
    brand = serializers.CharField()
    sku = serializers.CharField()
    weight = serializers.IntegerField()
    width = serializers.FloatField()
    height = serializers.FloatField()
    depth = serializers.FloatField()
    warranty_information = serializers.CharField()
    shipping_information = serializers.CharField()
    availability_status = serializers.CharField()
    return_policy = serializers.CharField()
    minimum_order_quantity = serializers.IntegerField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    barcode = serializers.CharField()
    qr_code = serializers.CharField()
    thumbnail = serializers.URLField()


class ProductCreateInputSerializer(serializers.Serializer):
    title = serializers.CharField()
    description = serializers.CharField()
    category = serializers.CharField()
    price = serializers.FloatField()
    discount_percentage = serializers.FloatField()
    rating = serializers.FloatField()
    stock = serializers.IntegerField()
    tags = serializers.CharField()
    brand = serializers.CharField()
    sku = serializers.CharField()
    weight = serializers.IntegerField()
    width = serializers.FloatField()
    height = serializers.FloatField()
    depth = serializers.FloatField()
    warranty_information = serializers.CharField()
    shipping_information = serializers.CharField()
    availability_status = serializers.CharField()
    return_policy = serializers.CharField()
    minimum_order_quantity = serializers.IntegerField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    barcode = serializers.CharField()
    qr_code = serializers.CharField()
    thumbnail = serializers.URLField()


class ProductUpdateInputSerializer(serializers.Serializer):
    title = serializers.CharField()
    description = serializers.CharField()
    category = serializers.CharField()
    price = serializers.FloatField()
    discount_percentage = serializers.FloatField()
    rating = serializers.FloatField()
    stock = serializers.IntegerField()
    tags = serializers.CharField()
    brand = serializers.CharField()
    sku = serializers.CharField()
    weight = serializers.IntegerField()
    width = serializers.FloatField()
    height = serializers.FloatField()
    depth = serializers.FloatField()
    warranty_information = serializers.CharField()
    shipping_information = serializers.CharField()
    availability_status = serializers.CharField()
    return_policy = serializers.CharField()
    minimum_order_quantity = serializers.IntegerField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    barcode = serializers.CharField()
    qr_code = serializers.CharField()
    thumbnail = serializers.URLField()


class ProductPartialUpdateInputSerializer(serializers.Serializer):
    title = serializers.CharField(required=False)
    description = serializers.CharField(required=False)
    category = serializers.CharField(required=False)
    price = serializers.FloatField(required=False)
    discount_percentage = serializers.FloatField(required=False)
    rating = serializers.FloatField(required=False)
    stock = serializers.IntegerField(required=False)
    tags = serializers.CharField(required=False)
    brand = serializers.CharField(required=False)
    sku = serializers.CharField(required=False)
    weight = serializers.IntegerField(required=False)
    width = serializers.FloatField(required=False)
    height = serializers.FloatField(required=False)
    depth = serializers.FloatField(required=False)
    warranty_information = serializers.CharField(required=False)
    shipping_information = serializers.CharField(required=False)
    availability_status = serializers.CharField(required=False)
    return_policy = serializers.CharField(required=False)
    minimum_order_quantity = serializers.IntegerField(required=False)
    created_at = serializers.DateTimeField(required=False)
    updated_at = serializers.DateTimeField(required=False)
    barcode = serializers.CharField(required=False)
    qr_code = serializers.CharField(required=False)
    thumbnail = serializers.URLField(required=False)


class ProductFilterOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    title = serializers.CharField()
    description = serializers.CharField()
    category = serializers.CharField()
    price = serializers.FloatField()
    discount_percentage = serializers.FloatField()
    rating = serializers.FloatField()
    stock = serializers.IntegerField()
    tags = serializers.CharField()
    brand = serializers.CharField()
    sku = serializers.CharField()
    weight = serializers.IntegerField()
    width = serializers.FloatField()
    height = serializers.FloatField()
    depth = serializers.FloatField()
    warranty_information = serializers.CharField()
    shipping_information = serializers.CharField()
    availability_status = serializers.CharField()
    return_policy = serializers.CharField()
    minimum_order_quantity = serializers.IntegerField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    barcode = serializers.CharField()
    qr_code = serializers.CharField()
    thumbnail = serializers.URLField()


class ProductFilterInputSerializer(serializers.Serializer):
    id = serializers.IntegerField(required=False)
    title = serializers.CharField(required=False)
    description = serializers.CharField(required=False)
    category = serializers.CharField(required=False)
    price = serializers.FloatField(required=False)
    discount_percentage = serializers.FloatField(required=False)
    rating = serializers.FloatField(required=False)
    stock = serializers.IntegerField(required=False)
    tags = serializers.CharField(required=False)
    brand = serializers.CharField(required=False)
    sku = serializers.CharField(required=False)
    weight = serializers.IntegerField(required=False)
    width = serializers.FloatField(required=False)
    height = serializers.FloatField(required=False)
    depth = serializers.FloatField(required=False)
    warranty_information = serializers.CharField(required=False)
    shipping_information = serializers.CharField(required=False)
    availability_status = serializers.CharField(required=False)
    return_policy = serializers.CharField(required=False)
    minimum_order_quantity = serializers.IntegerField(required=False)
    created_at = serializers.DateTimeField(required=False)
    updated_at = serializers.DateTimeField(required=False)
    barcode = serializers.CharField(required=False)
    qr_code = serializers.CharField(required=False)
    thumbnail = serializers.URLField(required=False)


class ProductStatsOutputSerializer(serializers.Serializer):
    category = serializers.CharField()
    count_products = serializers.IntegerField()
    avg_price = serializers.FloatField()
    max_price = serializers.FloatField()
    min_price = serializers.FloatField()
    avg_discount_percentage = serializers.FloatField()
    max_discount_percentage = serializers.FloatField()
    min_discount_percentage = serializers.FloatField()
    avg_rating = serializers.FloatField()
    max_rating = serializers.FloatField()
    min_rating = serializers.FloatField()
    sum_stock = serializers.IntegerField()
