from rest_framework import serializers


class RecipeListOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    name = serializers.CharField()
    ingredients = serializers.CharField()
    instructions = serializers.CharField()
    prep_time_minutes = serializers.IntegerField()
    cook_time_minutes = serializers.IntegerField()
    servings = serializers.IntegerField()
    difficulty = serializers.CharField()
    cuisine = serializers.CharField()
    calories_per_serving = serializers.IntegerField()
    tags = serializers.CharField()
    image = serializers.URLField()
    rating = serializers.FloatField()
    review_count = serializers.IntegerField()
    meal_type = serializers.CharField()
    user = serializers.IntegerField(source="user_id")


class RecipeDetailOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    name = serializers.CharField()
    ingredients = serializers.CharField()
    instructions = serializers.CharField()
    prep_time_minutes = serializers.IntegerField()
    cook_time_minutes = serializers.IntegerField()
    servings = serializers.IntegerField()
    difficulty = serializers.CharField()
    cuisine = serializers.CharField()
    calories_per_serving = serializers.IntegerField()
    tags = serializers.CharField()
    image = serializers.URLField()
    rating = serializers.FloatField()
    review_count = serializers.IntegerField()
    meal_type = serializers.CharField()
    user = serializers.IntegerField(source="user_id")


class RecipeSearchOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    name = serializers.CharField()
    ingredients = serializers.CharField()
    instructions = serializers.CharField()
    prep_time_minutes = serializers.IntegerField()
    cook_time_minutes = serializers.IntegerField()
    servings = serializers.IntegerField()
    difficulty = serializers.CharField()
    cuisine = serializers.CharField()
    calories_per_serving = serializers.IntegerField()
    tags = serializers.CharField()
    image = serializers.URLField()
    rating = serializers.FloatField()
    review_count = serializers.IntegerField()
    meal_type = serializers.CharField()
    user = serializers.IntegerField(source="user_id")


class RecipeCreateInputSerializer(serializers.Serializer):
    name = serializers.CharField()
    ingredients = serializers.CharField()
    instructions = serializers.CharField()
    prep_time_minutes = serializers.IntegerField()
    cook_time_minutes = serializers.IntegerField()
    servings = serializers.IntegerField()
    difficulty = serializers.CharField()
    cuisine = serializers.CharField()
    calories_per_serving = serializers.IntegerField()
    tags = serializers.CharField()
    image = serializers.URLField()
    rating = serializers.FloatField()
    review_count = serializers.IntegerField()
    meal_type = serializers.CharField()
    user = serializers.IntegerField()


class RecipeUpdateInputSerializer(serializers.Serializer):
    name = serializers.CharField()
    ingredients = serializers.CharField()
    instructions = serializers.CharField()
    prep_time_minutes = serializers.IntegerField()
    cook_time_minutes = serializers.IntegerField()
    servings = serializers.IntegerField()
    difficulty = serializers.CharField()
    cuisine = serializers.CharField()
    calories_per_serving = serializers.IntegerField()
    tags = serializers.CharField()
    image = serializers.URLField()
    rating = serializers.FloatField()
    review_count = serializers.IntegerField()
    meal_type = serializers.CharField()
    user = serializers.IntegerField()


class RecipePartialUpdateInputSerializer(serializers.Serializer):
    name = serializers.CharField(required=False)
    ingredients = serializers.CharField(required=False)
    instructions = serializers.CharField(required=False)
    prep_time_minutes = serializers.IntegerField(required=False)
    cook_time_minutes = serializers.IntegerField(required=False)
    servings = serializers.IntegerField(required=False)
    difficulty = serializers.CharField(required=False)
    cuisine = serializers.CharField(required=False)
    calories_per_serving = serializers.IntegerField(required=False)
    tags = serializers.CharField(required=False)
    image = serializers.URLField(required=False)
    rating = serializers.FloatField(required=False)
    review_count = serializers.IntegerField(required=False)
    meal_type = serializers.CharField(required=False)
    user = serializers.IntegerField(required=False)


class RecipeFilterOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    name = serializers.CharField()
    ingredients = serializers.CharField()
    instructions = serializers.CharField()
    prep_time_minutes = serializers.IntegerField()
    cook_time_minutes = serializers.IntegerField()
    servings = serializers.IntegerField()
    difficulty = serializers.CharField()
    cuisine = serializers.CharField()
    calories_per_serving = serializers.IntegerField()
    tags = serializers.CharField()
    image = serializers.URLField()
    rating = serializers.FloatField()
    review_count = serializers.IntegerField()
    meal_type = serializers.CharField()
    user = serializers.IntegerField(source="user_id")


class RecipeFilterInputSerializer(serializers.Serializer):
    id = serializers.IntegerField(required=False)
    name = serializers.CharField(required=False)
    ingredients = serializers.CharField(required=False)
    instructions = serializers.CharField(required=False)
    prep_time_minutes = serializers.IntegerField(required=False)
    cook_time_minutes = serializers.IntegerField(required=False)
    servings = serializers.IntegerField(required=False)
    difficulty = serializers.CharField(required=False)
    cuisine = serializers.CharField(required=False)
    calories_per_serving = serializers.IntegerField(required=False)
    tags = serializers.CharField(required=False)
    image = serializers.URLField(required=False)
    rating = serializers.FloatField(required=False)
    review_count = serializers.IntegerField(required=False)
    meal_type = serializers.CharField(required=False)
    user = serializers.IntegerField(required=False)

