from rest_framework import serializers


class DummyUserListOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    maiden_name = serializers.CharField()
    age = serializers.IntegerField()
    gender = serializers.CharField()
    email = serializers.EmailField()
    phone = serializers.CharField()
    username = serializers.CharField()
    password = serializers.CharField()
    birthday = serializers.DateField()
    image = serializers.URLField()
    blood_group = serializers.CharField()
    height = serializers.FloatField()
    weight = serializers.FloatField()
    eye_color = serializers.CharField()
    hair_color = serializers.CharField()
    hair_type = serializers.CharField()
    ip = serializers.CharField()
    address = serializers.CharField()
    city = serializers.CharField()
    state = serializers.CharField()
    state_code = serializers.CharField()
    postal_code = serializers.CharField()
    coordinates = serializers.CharField()
    country = serializers.CharField()
    mac_address = serializers.CharField()
    university = serializers.CharField()
    bank_card_expire = serializers.CharField()
    bank_card_number = serializers.CharField()
    bank_card_type = serializers.CharField()
    bank_currency = serializers.CharField()
    bank_iban = serializers.CharField()
    company_department = serializers.CharField()
    company_name = serializers.CharField()
    company_title = serializers.CharField()
    company_address = serializers.CharField()
    company_city = serializers.CharField()
    company_state = serializers.CharField()
    company_state_code = serializers.CharField()
    company_postal_code = serializers.CharField()
    company_coordinates = serializers.CharField()
    company_country = serializers.CharField()
    ein = serializers.CharField()
    ssn = serializers.CharField()
    user_agent = serializers.CharField()
    crypto_coint = serializers.CharField()
    crypto_wallet = serializers.CharField()
    crypto_network = serializers.CharField()
    role = serializers.CharField()


class DummyUserDetailOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    maiden_name = serializers.CharField()
    age = serializers.IntegerField()
    gender = serializers.CharField()
    email = serializers.EmailField()
    phone = serializers.CharField()
    username = serializers.CharField()
    password = serializers.CharField()
    birthday = serializers.DateField()
    image = serializers.URLField()
    blood_group = serializers.CharField()
    height = serializers.FloatField()
    weight = serializers.FloatField()
    eye_color = serializers.CharField()
    hair_color = serializers.CharField()
    hair_type = serializers.CharField()
    ip = serializers.CharField()
    address = serializers.CharField()
    city = serializers.CharField()
    state = serializers.CharField()
    state_code = serializers.CharField()
    postal_code = serializers.CharField()
    coordinates = serializers.CharField()
    country = serializers.CharField()
    mac_address = serializers.CharField()
    university = serializers.CharField()
    bank_card_expire = serializers.CharField()
    bank_card_number = serializers.CharField()
    bank_card_type = serializers.CharField()
    bank_currency = serializers.CharField()
    bank_iban = serializers.CharField()
    company_department = serializers.CharField()
    company_name = serializers.CharField()
    company_title = serializers.CharField()
    company_address = serializers.CharField()
    company_city = serializers.CharField()
    company_state = serializers.CharField()
    company_state_code = serializers.CharField()
    company_postal_code = serializers.CharField()
    company_coordinates = serializers.CharField()
    company_country = serializers.CharField()
    ein = serializers.CharField()
    ssn = serializers.CharField()
    user_agent = serializers.CharField()
    crypto_coint = serializers.CharField()
    crypto_wallet = serializers.CharField()
    crypto_network = serializers.CharField()
    role = serializers.CharField()


class DummyUserSearchOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    maiden_name = serializers.CharField()
    age = serializers.IntegerField()
    gender = serializers.CharField()
    email = serializers.EmailField()
    phone = serializers.CharField()
    username = serializers.CharField()
    password = serializers.CharField()
    birthday = serializers.DateField()
    image = serializers.URLField()
    blood_group = serializers.CharField()
    height = serializers.FloatField()
    weight = serializers.FloatField()
    eye_color = serializers.CharField()
    hair_color = serializers.CharField()
    hair_type = serializers.CharField()
    ip = serializers.CharField()
    address = serializers.CharField()
    city = serializers.CharField()
    state = serializers.CharField()
    state_code = serializers.CharField()
    postal_code = serializers.CharField()
    coordinates = serializers.CharField()
    country = serializers.CharField()
    mac_address = serializers.CharField()
    university = serializers.CharField()
    bank_card_expire = serializers.CharField()
    bank_card_number = serializers.CharField()
    bank_card_type = serializers.CharField()
    bank_currency = serializers.CharField()
    bank_iban = serializers.CharField()
    company_department = serializers.CharField()
    company_name = serializers.CharField()
    company_title = serializers.CharField()
    company_address = serializers.CharField()
    company_city = serializers.CharField()
    company_state = serializers.CharField()
    company_state_code = serializers.CharField()
    company_postal_code = serializers.CharField()
    company_coordinates = serializers.CharField()
    company_country = serializers.CharField()
    ein = serializers.CharField()
    ssn = serializers.CharField()
    user_agent = serializers.CharField()
    crypto_coint = serializers.CharField()
    crypto_wallet = serializers.CharField()
    crypto_network = serializers.CharField()
    role = serializers.CharField()


class DummyUserCreateInputSerializer(serializers.Serializer):
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    maiden_name = serializers.CharField()
    age = serializers.IntegerField()
    gender = serializers.CharField()
    email = serializers.EmailField()
    phone = serializers.CharField()
    username = serializers.CharField()
    password = serializers.CharField()
    birthday = serializers.DateField()
    image = serializers.URLField()
    blood_group = serializers.CharField()
    height = serializers.FloatField()
    weight = serializers.FloatField()
    eye_color = serializers.CharField()
    hair_color = serializers.CharField()
    hair_type = serializers.CharField()
    ip = serializers.CharField()
    address = serializers.CharField()
    city = serializers.CharField()
    state = serializers.CharField()
    state_code = serializers.CharField()
    postal_code = serializers.CharField()
    coordinates = serializers.CharField()
    country = serializers.CharField()
    mac_address = serializers.CharField()
    university = serializers.CharField()
    bank_card_expire = serializers.CharField()
    bank_card_number = serializers.CharField()
    bank_card_type = serializers.CharField()
    bank_currency = serializers.CharField()
    bank_iban = serializers.CharField()
    company_department = serializers.CharField()
    company_name = serializers.CharField()
    company_title = serializers.CharField()
    company_address = serializers.CharField()
    company_city = serializers.CharField()
    company_state = serializers.CharField()
    company_state_code = serializers.CharField()
    company_postal_code = serializers.CharField()
    company_coordinates = serializers.CharField()
    company_country = serializers.CharField()
    ein = serializers.CharField()
    ssn = serializers.CharField()
    user_agent = serializers.CharField()
    crypto_coint = serializers.CharField()
    crypto_wallet = serializers.CharField()
    crypto_network = serializers.CharField()
    role = serializers.CharField()


class DummyUserUpdateInputSerializer(serializers.Serializer):
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    maiden_name = serializers.CharField()
    age = serializers.IntegerField()
    gender = serializers.CharField()
    email = serializers.EmailField()
    phone = serializers.CharField()
    username = serializers.CharField()
    password = serializers.CharField()
    birthday = serializers.DateField()
    image = serializers.URLField()
    blood_group = serializers.CharField()
    height = serializers.FloatField()
    weight = serializers.FloatField()
    eye_color = serializers.CharField()
    hair_color = serializers.CharField()
    hair_type = serializers.CharField()
    ip = serializers.CharField()
    address = serializers.CharField()
    city = serializers.CharField()
    state = serializers.CharField()
    state_code = serializers.CharField()
    postal_code = serializers.CharField()
    coordinates = serializers.CharField()
    country = serializers.CharField()
    mac_address = serializers.CharField()
    university = serializers.CharField()
    bank_card_expire = serializers.CharField()
    bank_card_number = serializers.CharField()
    bank_card_type = serializers.CharField()
    bank_currency = serializers.CharField()
    bank_iban = serializers.CharField()
    company_department = serializers.CharField()
    company_name = serializers.CharField()
    company_title = serializers.CharField()
    company_address = serializers.CharField()
    company_city = serializers.CharField()
    company_state = serializers.CharField()
    company_state_code = serializers.CharField()
    company_postal_code = serializers.CharField()
    company_coordinates = serializers.CharField()
    company_country = serializers.CharField()
    ein = serializers.CharField()
    ssn = serializers.CharField()
    user_agent = serializers.CharField()
    crypto_coint = serializers.CharField()
    crypto_wallet = serializers.CharField()
    crypto_network = serializers.CharField()
    role = serializers.CharField()


class DummyUserPartialUpdateInputSerializer(serializers.Serializer):
    first_name = serializers.CharField(required=False)
    last_name = serializers.CharField(required=False)
    maiden_name = serializers.CharField(required=False)
    age = serializers.IntegerField(required=False)
    gender = serializers.CharField(required=False)
    email = serializers.EmailField(required=False)
    phone = serializers.CharField(required=False)
    username = serializers.CharField(required=False)
    password = serializers.CharField(required=False)
    birthday = serializers.DateField(required=False)
    image = serializers.URLField(required=False)
    blood_group = serializers.CharField(required=False)
    height = serializers.FloatField(required=False)
    weight = serializers.FloatField(required=False)
    eye_color = serializers.CharField(required=False)
    hair_color = serializers.CharField(required=False)
    hair_type = serializers.CharField(required=False)
    ip = serializers.CharField(required=False)
    address = serializers.CharField(required=False)
    city = serializers.CharField(required=False)
    state = serializers.CharField(required=False)
    state_code = serializers.CharField(required=False)
    postal_code = serializers.CharField(required=False)
    coordinates = serializers.CharField(required=False)
    country = serializers.CharField(required=False)
    mac_address = serializers.CharField(required=False)
    university = serializers.CharField(required=False)
    bank_card_expire = serializers.CharField(required=False)
    bank_card_number = serializers.CharField(required=False)
    bank_card_type = serializers.CharField(required=False)
    bank_currency = serializers.CharField(required=False)
    bank_iban = serializers.CharField(required=False)
    company_department = serializers.CharField(required=False)
    company_name = serializers.CharField(required=False)
    company_title = serializers.CharField(required=False)
    company_address = serializers.CharField(required=False)
    company_city = serializers.CharField(required=False)
    company_state = serializers.CharField(required=False)
    company_state_code = serializers.CharField(required=False)
    company_postal_code = serializers.CharField(required=False)
    company_coordinates = serializers.CharField(required=False)
    company_country = serializers.CharField(required=False)
    ein = serializers.CharField(required=False)
    ssn = serializers.CharField(required=False)
    user_agent = serializers.CharField(required=False)
    crypto_coint = serializers.CharField(required=False)
    crypto_wallet = serializers.CharField(required=False)
    crypto_network = serializers.CharField(required=False)
    role = serializers.CharField(required=False)


class DummyUserFilterOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    maiden_name = serializers.CharField()
    age = serializers.IntegerField()
    gender = serializers.CharField()
    email = serializers.EmailField()
    phone = serializers.CharField()
    username = serializers.CharField()
    password = serializers.CharField()
    birthday = serializers.DateField()
    image = serializers.URLField()
    blood_group = serializers.CharField()
    height = serializers.FloatField()
    weight = serializers.FloatField()
    eye_color = serializers.CharField()
    hair_color = serializers.CharField()
    hair_type = serializers.CharField()
    ip = serializers.CharField()
    address = serializers.CharField()
    city = serializers.CharField()
    state = serializers.CharField()
    state_code = serializers.CharField()
    postal_code = serializers.CharField()
    coordinates = serializers.CharField()
    country = serializers.CharField()
    mac_address = serializers.CharField()
    university = serializers.CharField()
    bank_card_expire = serializers.CharField()
    bank_card_number = serializers.CharField()
    bank_card_type = serializers.CharField()
    bank_currency = serializers.CharField()
    bank_iban = serializers.CharField()
    company_department = serializers.CharField()
    company_name = serializers.CharField()
    company_title = serializers.CharField()
    company_address = serializers.CharField()
    company_city = serializers.CharField()
    company_state = serializers.CharField()
    company_state_code = serializers.CharField()
    company_postal_code = serializers.CharField()
    company_coordinates = serializers.CharField()
    company_country = serializers.CharField()
    ein = serializers.CharField()
    ssn = serializers.CharField()
    user_agent = serializers.CharField()
    crypto_coint = serializers.CharField()
    crypto_wallet = serializers.CharField()
    crypto_network = serializers.CharField()
    role = serializers.CharField()


class DummyUserFilterInputSerializer(serializers.Serializer):
    id = serializers.IntegerField(required=False)
    first_name = serializers.CharField(required=False)
    last_name = serializers.CharField(required=False)
    maiden_name = serializers.CharField(required=False)
    age = serializers.IntegerField(required=False)
    gender = serializers.CharField(required=False)
    email = serializers.EmailField(required=False)
    phone = serializers.CharField(required=False)
    username = serializers.CharField(required=False)
    password = serializers.CharField(required=False)
    birthday = serializers.DateField(required=False)
    image = serializers.URLField(required=False)
    blood_group = serializers.CharField(required=False)
    height = serializers.FloatField(required=False)
    weight = serializers.FloatField(required=False)
    eye_color = serializers.CharField(required=False)
    hair_color = serializers.CharField(required=False)
    hair_type = serializers.CharField(required=False)
    ip = serializers.IPAddressField(required=False)
    address = serializers.CharField(required=False)
    city = serializers.CharField(required=False)
    state = serializers.CharField(required=False)
    state_code = serializers.CharField(required=False)
    postal_code = serializers.CharField(required=False)
    coordinates = serializers.CharField(required=False)
    country = serializers.CharField(required=False)
    mac_address = serializers.CharField(required=False)
    university = serializers.CharField(required=False)
    bank_card_expire = serializers.CharField(required=False)
    bank_card_number = serializers.CharField(required=False)
    bank_card_type = serializers.CharField(required=False)
    bank_currency = serializers.CharField(required=False)
    bank_iban = serializers.CharField(required=False)
    company_department = serializers.CharField(required=False)
    company_name = serializers.CharField(required=False)
    company_title = serializers.CharField(required=False)
    company_address = serializers.CharField(required=False)
    company_city = serializers.CharField(required=False)
    company_state = serializers.CharField(required=False)
    company_state_code = serializers.CharField(required=False)
    company_postal_code = serializers.CharField(required=False)
    company_coordinates = serializers.CharField(required=False)
    company_country = serializers.CharField(required=False)
    ein = serializers.CharField(required=False)
    ssn = serializers.CharField(required=False)
    user_agent = serializers.CharField(required=False)
    crypto_coint = serializers.CharField(required=False)
    crypto_wallet = serializers.CharField(required=False)
    crypto_network = serializers.CharField(required=False)
    role = serializers.CharField(required=False)


class DummyUserRoleGroupSerializer(serializers.Serializer):
    role = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserCompanyStateGroupSerializer(serializers.Serializer):
    company_state = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserCompanyDepartmentGroupSerializer(serializers.Serializer):
    company_department = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserBankCardTypeGroupSerializer(serializers.Serializer):
    bank_card_type = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserUniversityGroupSerializer(serializers.Serializer):
    university = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserStateGroupSerializer(serializers.Serializer):
    state = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserBloodGroupGroupSerializer(serializers.Serializer):
    blood_group = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserGenderGroupSerializer(serializers.Serializer):
    gender = serializers.CharField()
    count_users = serializers.IntegerField()


class DummyUserOtherGroupSerializer(serializers.Serializer):
    min_age = serializers.IntegerField()
    max_age = serializers.IntegerField()
    avg_age = serializers.FloatField()
    min_height = serializers.FloatField()
    max_height = serializers.FloatField()
    avg_height = serializers.FloatField()
    min_weight = serializers.FloatField()
    max_weight = serializers.FloatField()
    avg_weight = serializers.FloatField()


class DummyUserStatsOutputSerializer(serializers.Serializer):
    role_group = DummyUserRoleGroupSerializer(many=True)
    company_state_group = DummyUserCompanyStateGroupSerializer(many=True)
    company_department_group = DummyUserCompanyDepartmentGroupSerializer(many=True)
    bank_card_type_group = DummyUserBankCardTypeGroupSerializer(many=True)
    university_group = DummyUserUniversityGroupSerializer(many=True)
    state_group = DummyUserStateGroupSerializer(many=True)
    blood_group_group = DummyUserBloodGroupGroupSerializer(many=True)
    gender_group = DummyUserGenderGroupSerializer(many=True)
    other_group = DummyUserOtherGroupSerializer()
