from django.urls import path
from dummy_api import views

urlpatterns = [
    path("users_list", views.users_list, name="users_list"),
    path("users_detail/<int:pk>", views.users_detail, name="users_detail"),
    path("users_search", views.users_search, name="users_search"),
    path("users_create", views.users_create, name="users_create"),
    path("users_update/<int:pk>", views.users_update, name="users_update"),
    path(
        "users_partial_update/<int:pk>",
        views.users_partial_update,
        name="users_partial_update",
    ),
    path("users_filter", views.users_filter, name="users_filter"),
    path("users_delete/<int:pk>", views.users_delete, name="users_delete"),
    path("users_stats", views.users_stats, name="users_stats"),
    path("todos_list", views.todos_list, name="todos_list"),
    path("todos_detail/<int:pk>", views.todos_detail, name="todos_detail"),
    path("todos_search", views.todos_search, name="todos_search"),
    path("todos_create", views.todos_create, name="todos_create"),
    path("todos_update/<int:pk>", views.todos_update, name="todos_update"),
    path(
        "todos_partial_update/<int:pk>",
        views.todos_partial_update,
        name="todos_partial_update",
    ),
    path("todos_filter", views.todos_filter, name="todos_filter"),
    path("todos_delete/<int:pk>", views.todos_delete, name="todos_delete"),
    path("todos_stats", views.todos_stats, name="todos_stats"),
    path("recipes_list", views.recipes_list, name="recipes_list"),
    path("recipes_detail/<int:pk>", views.recipes_detail, name="recipes_detail"),
    path("recipes_search", views.recipes_search, name="recipes_search"),
    path("recipes_create", views.recipes_create, name="recipes_create"),
    path("recipes_update/<int:pk>", views.recipes_update, name="recipes_update"),
    path(
        "recipes_partial_update/<int:pk>",
        views.recipes_partial_update,
        name="recipes_partial_update",
    ),
    path("recipes_filter", views.recipes_filter, name="recipes_filter"),
    path("recipes_delete/<int:pk>", views.recipes_delete, name="recipes_delete"),
    path("recipes_stats", views.recipes_stats, name="recipes_stats"),
    path("quotes_list", views.quotes_list, name="quotes_list"),
    path("quotes_detail/<int:pk>", views.quotes_detail, name="quotes_detail"),
    path("quotes_search", views.quotes_search, name="quotes_search"),
    path("quotes_create", views.quotes_create, name="quotes_create"),
    path("quotes_update/<int:pk>", views.quotes_update, name="quotes_update"),
    path(
        "quotes_partial_update/<int:pk>",
        views.quotes_partial_update,
        name="quotes_partial_update",
    ),
    path("quotes_filter", views.quotes_filter, name="quotes_filter"),
    path("quotes_delete/<int:pk>", views.quotes_delete, name="quotes_delete"),
    path("quotes_stats", views.quotes_stats, name="quotes_stats"),
    path("products_list", views.products_list, name="products_list"),
    path("products_detail/<int:pk>", views.products_detail, name="products_detail"),
    path("products_search", views.products_search, name="products_search"),
    path("products_create", views.products_create, name="products_create"),
    path("products_update/<int:pk>", views.products_update, name="products_update"),
    path(
        "products_partial_update/<int:pk>",
        views.products_partial_update,
        name="products_partial_update",
    ),
    path("products_filter", views.products_filter, name="products_filter"),
    path("products_delete/<int:pk>", views.products_delete, name="products_delete"),
    path("products_stats", views.products_stats, name="products_stats"),
    path("reviews_list", views.reviews_list, name="reviews_list"),
    path("reviews_detail/<int:pk>", views.reviews_detail, name="reviews_detail"),
    path("reviews_search", views.reviews_search, name="reviews_search"),
    path("reviews_create", views.reviews_create, name="reviews_create"),
    path("reviews_update/<int:pk>", views.reviews_update, name="reviews_update"),
    path(
        "reviews_partial_update/<int:pk>",
        views.reviews_partial_update,
        name="reviews_partial_update",
    ),
    path("reviews_filter", views.reviews_filter, name="reviews_filter"),
    path("reviews_delete/<int:pk>", views.reviews_delete, name="reviews_delete"),
    path("reviews_stats", views.reviews_stats, name="reviews_stats"),
    path("posts_list", views.posts_list, name="posts_list"),
    path("posts_detail/<int:pk>", views.posts_detail, name="posts_detail"),
    path("posts_search", views.posts_search, name="posts_search"),
    path("posts_create", views.posts_create, name="posts_create"),
    path("posts_update/<int:pk>", views.posts_update, name="posts_update"),
    path(
        "posts_partial_update/<int:pk>",
        views.posts_partial_update,
        name="posts_partial_update",
    ),
    path("posts_filter", views.posts_filter, name="posts_filter"),
    path("posts_delete/<int:pk>", views.posts_delete, name="posts_delete"),
    path("posts_stats", views.posts_stats, name="posts_stats"),
    path("comments_list", views.comments_list, name="comments_list"),
    path("comments_detail/<int:pk>", views.comments_detail, name="comments_detail"),
    path("comments_search", views.comments_search, name="comments_search"),
    path("comments_create", views.comments_create, name="comments_create"),
    path("comments_update/<int:pk>", views.comments_update, name="comments_update"),
    path(
        "comments_partial_update/<int:pk>",
        views.comments_partial_update,
        name="comments_partial_update",
    ),
    path("comments_filter", views.comments_filter, name="comments_filter"),
    path("comments_delete/<int:pk>", views.comments_delete, name="comments_delete"),
    path("comments_stats", views.comments_stats, name="comments_stats"),
    path("carts_list", views.carts_list, name="carts_list"),
    path("carts_detail/<int:pk>", views.carts_detail, name="carts_detail"),
    path("carts_search", views.carts_search, name="carts_search"),
    path("carts_create", views.carts_create, name="carts_create"),
    path("carts_update/<int:pk>", views.carts_update, name="carts_update"),
    path(
        "carts_partial_update/<int:pk>",
        views.carts_partial_update,
        name="carts_partial_update",
    ),
    path("carts_filter", views.carts_filter, name="carts_filter"),
    path("carts_delete/<int:pk>", views.carts_delete, name="carts_delete"),
    path("carts_stats", views.carts_stats, name="carts_stats"),
    path("profile/<int:pk>", views.profile, name="profile"),
]
