from django.urls import path
from placeholder_api import views

urlpatterns = [
    path("comments_list", views.comments_list, name="comments_list"),
    path("comments_detail/<int:pk>", views.comments_detail, name="comments_detail"),
    path("comments_search", views.comments_search, name="comments_search"),
    path("comments_create", views.comments_create, name="comments_create"),
    path("comments_update/<int:pk>", views.comments_update, name="comments_update"),
    path(
        "comments_partial_update/<int:pk>",
        views.comments_partial_update,
        name="comments_partial_update",
    ),
    path("comments_filter", views.comments_filter, name="comments_filter"),
    path("comments_delete/<int:pk>", views.comments_delete, name="comments_delete"),
    path("comments_stats", views.comments_stats, name="comments_stats"),
    path("users_list", views.users_list, name="users_list"),
    path("users_detail/<int:pk>", views.users_detail, name="users_detail"),
    path("users_search", views.users_search, name="users_search"),
    path("users_create", views.users_create, name="users_create"),
    path("users_update/<int:pk>", views.users_update, name="users_update"),
    path(
        "users_partial_update/<int:pk>",
        views.users_partial_update,
        name="users_partial_update",
    ),
    path("users_filter", views.users_filter, name="users_filter"),
    path("users_delete/<int:pk>", views.users_delete, name="users_delete"),
    path("users_stats", views.users_stats, name="users_stats"),
    path("todos_list", views.todos_list, name="todos_list"),
    path("todos_detail/<int:pk>", views.todos_detail, name="todos_detail"),
    path("todos_search", views.todos_search, name="todos_search"),
    path("todos_create", views.todos_create, name="todos_create"),
    path("todos_update/<int:pk>", views.todos_update, name="todos_update"),
    path(
        "todos_partial_update/<int:pk>",
        views.todos_partial_update,
        name="todos_partial_update",
    ),
    path("todos_filter", views.todos_filter, name="todos_filter"),
    path("todos_delete/<int:pk>", views.todos_delete, name="todos_delete"),
    path("todos_stats", views.todos_stats, name="todos_stats"),
    path("albums_list", views.albums_list, name="albums_list"),
    path("albums_detail/<int:pk>", views.albums_detail, name="albums_detail"),
    path("albums_search", views.albums_search, name="albums_search"),
    path("albums_create", views.albums_create, name="albums_create"),
    path("albums_update/<int:pk>", views.albums_update, name="albums_update"),
    path(
        "albums_partial_update/<int:pk>",
        views.albums_partial_update,
        name="albums_partial_update",
    ),
    path("albums_filter", views.albums_filter, name="albums_filter"),
    path("albums_delete/<int:pk>", views.albums_delete, name="albums_delete"),
    path("albums_stats", views.albums_stats, name="albums_stats"),
    path("photos_list", views.photos_list, name="photos_list"),
    path("photos_detail/<int:pk>", views.photos_detail, name="photos_detail"),
    path("photos_search", views.photos_search, name="photos_search"),
    path("photos_create", views.photos_create, name="photos_create"),
    path("photos_update/<int:pk>", views.photos_update, name="photos_update"),
    path(
        "photos_partial_update/<int:pk>",
        views.photos_partial_update,
        name="photos_partial_update",
    ),
    path("photos_filter", views.photos_filter, name="photos_filter"),
    path("photos_delete/<int:pk>", views.photos_delete, name="photos_delete"),
    path("photos_stats", views.photos_stats, name="photos_stats"),
    path("posts_list", views.posts_list, name="posts_list"),
    path("posts_detail/<int:pk>", views.posts_detail, name="posts_detail"),
    path("posts_search", views.posts_search, name="posts_search"),
    path("posts_create", views.posts_create, name="posts_create"),
    path("posts_update/<int:pk>", views.posts_update, name="posts_update"),
    path(
        "posts_partial_update/<int:pk>",
        views.posts_partial_update,
        name="posts_partial_update",
    ),
    path("posts_filter", views.posts_filter, name="posts_filter"),
    path("posts_delete/<int:pk>", views.posts_delete, name="posts_delete"),
    path("posts_stats", views.posts_stats, name="posts_stats"),
    path("profile/<int:pk>", views.profile, name="profile"),
    path("profiles_export_csv", views.profiles_export_csv, name="profiles_export_csv"),
    path("healthcheck", views.healthcheck, name="healthcheck"),
]
