from rest_framework import serializers


class TasksTaskListOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    subject = serializers.CharField()
    description = serializers.CharField()
    start_date = serializers.DateField()
    due_date = serializers.DateField(allow_null=True)
    is_private = serializers.BooleanField()
    done_percent = serializers.IntegerField()
    closed_on = serializers.DateTimeField(allow_null=True)
    spent_days = serializers.IntegerField(allow_null=True)
    estimated_days = serializers.IntegerField(allow_null=True)
    parent = serializers.IntegerField(source="parent_id", allow_null=True)
    category = serializers.IntegerField(source="category_id")
    assigned_to = serializers.IntegerField(source="assigned_to_id")
    author = serializers.IntegerField(source="author_id")
    priority = serializers.IntegerField(source="priority_id")
    status = serializers.IntegerField(source="status_id")
    project = serializers.IntegerField(source="project_id")
    created_on = serializers.DateTimeField()
    updated_on = serializers.DateTimeField()


class TasksTaskDetailOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    subject = serializers.CharField()
    description = serializers.CharField()
    start_date = serializers.DateField()
    due_date = serializers.DateField(allow_null=True)
    is_private = serializers.BooleanField()
    done_percent = serializers.IntegerField()
    closed_on = serializers.DateTimeField(allow_null=True)
    spent_days = serializers.IntegerField(allow_null=True)
    estimated_days = serializers.IntegerField(allow_null=True)
    parent = serializers.IntegerField(source="parent_id", allow_null=True)
    category = serializers.IntegerField(source="category_id")
    assigned_to = serializers.IntegerField(source="assigned_to_id")
    author = serializers.IntegerField(source="author_id")
    priority = serializers.IntegerField(source="priority_id")
    status = serializers.IntegerField(source="status_id")
    project = serializers.IntegerField(source="project_id")
    created_on = serializers.DateTimeField()
    updated_on = serializers.DateTimeField()


class TasksTaskSearchOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    subject = serializers.CharField()
    description = serializers.CharField()
    start_date = serializers.DateField()
    due_date = serializers.DateField(allow_null=True)
    is_private = serializers.BooleanField()
    done_percent = serializers.IntegerField()
    closed_on = serializers.DateTimeField(allow_null=True)
    spent_days = serializers.IntegerField(allow_null=True)
    estimated_days = serializers.IntegerField(allow_null=True)
    parent = serializers.IntegerField(source="parent_id", allow_null=True)
    category = serializers.IntegerField(source="category_id")
    assigned_to = serializers.IntegerField(source="assigned_to_id")
    author = serializers.IntegerField(source="author_id")
    priority = serializers.IntegerField(source="priority_id")
    status = serializers.IntegerField(source="status_id")
    project = serializers.IntegerField(source="project_id")
    created_on = serializers.DateTimeField()
    updated_on = serializers.DateTimeField()


class TasksTaskCreateInputSerializer(serializers.Serializer):
    subject = serializers.CharField()
    description = serializers.CharField()
    start_date = serializers.DateField()
    due_date = serializers.DateField(required=False, allow_null=True)
    is_private = serializers.BooleanField()
    done_percent = serializers.IntegerField(default=0)
    closed_on = serializers.DateTimeField(required=False, allow_null=True)
    spent_days = serializers.IntegerField(required=False, allow_null=True)
    estimated_days = serializers.IntegerField(required=False, allow_null=True)
    parent = serializers.IntegerField(required=False, allow_null=True)
    category = serializers.IntegerField()
    assigned_to = serializers.IntegerField()
    author = serializers.IntegerField()
    priority = serializers.IntegerField()
    status = serializers.IntegerField()
    project = serializers.IntegerField()


class TasksTaskUpdateInputSerializer(serializers.Serializer):
    subject = serializers.CharField()
    description = serializers.CharField()
    start_date = serializers.DateField()
    due_date = serializers.DateField(required=False, allow_null=True)
    is_private = serializers.BooleanField()
    done_percent = serializers.IntegerField()
    closed_on = serializers.DateTimeField(required=False, allow_null=True)
    spent_days = serializers.IntegerField(required=False, allow_null=True)
    estimated_days = serializers.IntegerField(required=False, allow_null=True)
    parent = serializers.IntegerField(required=False, allow_null=True)
    category = serializers.IntegerField()
    assigned_to = serializers.IntegerField()
    author = serializers.IntegerField()
    priority = serializers.IntegerField()
    status = serializers.IntegerField()
    project = serializers.IntegerField()


class TasksTaskPartialUpdateInputSerializer(serializers.Serializer):
    subject = serializers.CharField(required=False)
    description = serializers.CharField(required=False)
    start_date = serializers.DateField(required=False)
    due_date = serializers.DateField(required=False, allow_null=True)
    is_private = serializers.BooleanField(required=False)
    done_percent = serializers.IntegerField(required=False)
    closed_on = serializers.DateTimeField(required=False, allow_null=True)
    spent_days = serializers.IntegerField(required=False, allow_null=True)
    estimated_days = serializers.IntegerField(required=False, allow_null=True)
    parent = serializers.IntegerField(required=False, allow_null=True)
    category = serializers.IntegerField(required=False)
    assigned_to = serializers.IntegerField(required=False)
    author = serializers.IntegerField(required=False)
    priority = serializers.IntegerField(required=False)
    status = serializers.IntegerField(required=False)
    project = serializers.IntegerField(required=False)


class TasksTaskFilterOutputSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    subject = serializers.CharField()
    description = serializers.CharField()
    start_date = serializers.DateField()
    due_date = serializers.DateField(allow_null=True)
    is_private = serializers.BooleanField()
    done_percent = serializers.IntegerField()
    closed_on = serializers.DateTimeField(allow_null=True)
    spent_days = serializers.IntegerField(allow_null=True)
    estimated_days = serializers.IntegerField(allow_null=True)
    parent = serializers.IntegerField(source="parent_id", allow_null=True)
    category = serializers.IntegerField(source="category_id")
    assigned_to = serializers.IntegerField(source="assigned_to_id")
    author = serializers.IntegerField(source="author_id")
    priority = serializers.IntegerField(source="priority_id")
    status = serializers.IntegerField(source="status_id")
    project = serializers.IntegerField(source="project_id")
    created_on = serializers.DateTimeField()
    updated_on = serializers.DateTimeField()


class TasksTaskFilterInputSerializer(serializers.Serializer):
    id = serializers.IntegerField(required=False)
    subject = serializers.CharField(required=False)
    is_private = serializers.BooleanField(required=False, allow_null=True)
    category = serializers.IntegerField(required=False)
    assigned_to = serializers.IntegerField(required=False)
    author = serializers.IntegerField(required=False)
    priority = serializers.IntegerField(required=False)
    status = serializers.IntegerField(required=False)
    project = serializers.IntegerField(required=False)


class TasksTaskStatsOutputSerializer(serializers.Serializer):
    project = serializers.IntegerField(source="project_id")
    count_tasks = serializers.IntegerField()
