from django.urls import path
from tasks_api import views

urlpatterns = [
    path("statuses_list", views.statuses_list, name="statuses_list"),
    path("statuses_detail/<int:pk>", views.statuses_detail, name="statuses_detail"),
    path("statuses_search", views.statuses_search, name="statuses_search"),
    path("statuses_create", views.statuses_create, name="statuses_create"),
    path("statuses_update/<int:pk>", views.statuses_update, name="statuses_update"),
    path(
        "statuses_partial_update/<int:pk>",
        views.statuses_partial_update,
        name="statuses_partial_update",
    ),
    path("statuses_filter", views.statuses_filter, name="statuses_filter"),
    path("statuses_delete/<int:pk>", views.statuses_delete, name="statuses_delete"),
    path("statuses_stats", views.statuses_stats, name="statuses_stats"),
    path("priorities_list", views.priorities_list, name="priorities_list"),
    path(
        "priorities_detail/<int:pk>", views.priorities_detail, name="priorities_detail"
    ),
    path("priorities_search", views.priorities_search, name="priorities_search"),
    path("priorities_create", views.priorities_create, name="priorities_create"),
    path(
        "priorities_update/<int:pk>", views.priorities_update, name="priorities_update"
    ),
    path(
        "priorities_partial_update/<int:pk>",
        views.priorities_partial_update,
        name="priorities_partial_update",
    ),
    path("priorities_filter", views.priorities_filter, name="priorities_filter"),
    path(
        "priorities_delete/<int:pk>", views.priorities_delete, name="priorities_delete"
    ),
    path("priorities_stats", views.priorities_stats, name="priorities_stats"),
    path("categories_list", views.categories_list, name="categories_list"),
    path(
        "categories_detail/<int:pk>", views.categories_detail, name="categories_detail"
    ),
    path("categories_search", views.categories_search, name="categories_search"),
    path("categories_create", views.categories_create, name="categories_create"),
    path(
        "categories_update/<int:pk>", views.categories_update, name="categories_update"
    ),
    path(
        "categories_partial_update/<int:pk>",
        views.categories_partial_update,
        name="categories_partial_update",
    ),
    path("categories_filter", views.categories_filter, name="categories_filter"),
    path(
        "categories_delete/<int:pk>", views.categories_delete, name="categories_delete"
    ),
    path("categories_stats", views.categories_stats, name="categories_stats"),
    path("roles_list", views.roles_list, name="roles_list"),
    path("roles_detail/<int:pk>", views.roles_detail, name="roles_detail"),
    path("roles_search", views.roles_search, name="roles_search"),
    path("roles_create", views.roles_create, name="roles_create"),
    path("roles_update/<int:pk>", views.roles_update, name="roles_update"),
    path(
        "roles_partial_update/<int:pk>",
        views.roles_partial_update,
        name="roles_partial_update",
    ),
    path("roles_filter", views.roles_filter, name="roles_filter"),
    path("roles_delete/<int:pk>", views.roles_delete, name="roles_delete"),
    path("roles_stats", views.roles_stats, name="roles_stats"),
    path("groups_list", views.groups_list, name="groups_list"),
    path("groups_detail/<int:pk>", views.groups_detail, name="groups_detail"),
    path("groups_search", views.groups_search, name="groups_search"),
    path("groups_create", views.groups_create, name="groups_create"),
    path("groups_update/<int:pk>", views.groups_update, name="groups_update"),
    path(
        "groups_partial_update/<int:pk>",
        views.groups_partial_update,
        name="groups_partial_update",
    ),
    path("groups_filter", views.groups_filter, name="groups_filter"),
    path("groups_delete/<int:pk>", views.groups_delete, name="groups_delete"),
    path("groups_stats", views.groups_stats, name="groups_stats"),
    path("projects_list", views.projects_list, name="projects_list"),
    path("projects_detail/<int:pk>", views.projects_detail, name="projects_detail"),
    path("projects_search", views.projects_search, name="projects_search"),
    path("projects_create", views.projects_create, name="projects_create"),
    path("projects_update/<int:pk>", views.projects_update, name="projects_update"),
    path(
        "projects_partial_update/<int:pk>",
        views.projects_partial_update,
        name="projects_partial_update",
    ),
    path("projects_filter", views.projects_filter, name="projects_filter"),
    path("projects_delete/<int:pk>", views.projects_delete, name="projects_delete"),
    path("projects_stats", views.projects_stats, name="projects_stats"),
    path("tasks_users_list", views.tasks_users_list, name="tasks_users_list"),
    path(
        "tasks_users_detail/<int:pk>",
        views.tasks_users_detail,
        name="tasks_users_detail",
    ),
    path("tasks_users_search", views.tasks_users_search, name="tasks_users_search"),
    path("tasks_users_create", views.tasks_users_create, name="tasks_users_create"),
    path(
        "tasks_users_update/<int:pk>",
        views.tasks_users_update,
        name="tasks_users_update",
    ),
    path(
        "tasks_users_partial_update/<int:pk>",
        views.tasks_users_partial_update,
        name="tasks_users_partial_update",
    ),
    path("tasks_users_filter", views.tasks_users_filter, name="tasks_users_filter"),
    path(
        "tasks_users_delete/<int:pk>",
        views.tasks_users_delete,
        name="tasks_users_delete",
    ),
    path("tasks_users_stats", views.tasks_users_stats, name="tasks_users_stats"),
    path("tasks_list", views.tasks_list, name="tasks_list"),
    path("tasks_detail/<int:pk>", views.tasks_detail, name="tasks_detail"),
    path("tasks_search", views.tasks_search, name="tasks_search"),
    path("tasks_create", views.tasks_create, name="tasks_create"),
    path("tasks_update/<int:pk>", views.tasks_update, name="tasks_update"),
    path(
        "tasks_partial_update/<int:pk>",
        views.tasks_partial_update,
        name="tasks_partial_update",
    ),
    path("tasks_filter", views.tasks_filter, name="tasks_filter"),
    path("tasks_delete/<int:pk>", views.tasks_delete, name="tasks_delete"),
    path("tasks_stats", views.tasks_stats, name="tasks_stats"),
    path("news_list", views.news_list, name="news_list"),
    path("news_detail/<int:pk>", views.news_detail, name="news_detail"),
    path("news_search", views.news_search, name="news_search"),
    path("news_create", views.news_create, name="news_create"),
    path("news_update/<int:pk>", views.news_update, name="news_update"),
    path(
        "news_partial_update/<int:pk>",
        views.news_partial_update,
        name="news_partial_update",
    ),
    path("news_filter", views.news_filter, name="news_filter"),
    path("news_delete/<int:pk>", views.news_delete, name="news_delete"),
    path("news_stats", views.news_stats, name="news_stats"),
    path("comments_list", views.comments_list, name="comments_list"),
    path("comments_detail/<int:pk>", views.comments_detail, name="comments_detail"),
    path("comments_search", views.comments_search, name="comments_search"),
    path("comments_create", views.comments_create, name="comments_create"),
    path("comments_update/<int:pk>", views.comments_update, name="comments_update"),
    path(
        "comments_partial_update/<int:pk>",
        views.comments_partial_update,
        name="comments_partial_update",
    ),
    path("comments_filter", views.comments_filter, name="comments_filter"),
    path("comments_delete/<int:pk>", views.comments_delete, name="comments_delete"),
    path("comments_stats", views.comments_stats, name="comments_stats"),
    path("profile/<int:pk>", views.profile, name="profile"),
]
