name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13t", "3.14t"]
    name: Run tests. OS ${{ matrix.os }}. Python ${{ matrix.python-version }}.
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          cd djangotutorial
          uv venv
          uv pip install -r pyproject.toml --all-extras
          uv run ruff check
          uv run ruff format --check
          uv run python manage.py test --parallel
          uv run coverage run -p --source='.' manage.py test --parallel
          uv run coverage combine
          uv run coverage report

  workflow-telemetry-action:
    runs-on: ubuntu-latest
    name: Collect Workflow Telemetry
    steps:
      - name: Collect Workflow Telemetry
        uses: ycfreeman/workflow-telemetry-action@v3.0.2
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Setup server and wrk
        run: |
          cd djangotutorial
          docker compose up -d
          sudo apt install wrk
      - name: Run wrk
        run: |
          wrk -c 100 -t 4 -d 30 http://127.0.0.1:8000/placeholder_api/comments_list

  mutation-test:
    runs-on: ubuntu-latest
    name: Run mutation tests
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: 3.14t
      - name: Run mutation tests
        run: |
          cd djangotutorial
          uv venv
          uv pip install -r pyproject.toml --all-extras
          uv run cosmic-ray init cosmic-ray.toml cosmic-ray.sqlite3
          uv run cosmic-ray --verbosity=INFO baseline cosmic-ray.toml
          uv run cr-report cosmic-ray.sqlite3 --show-pending
          uv run cosmic-ray exec cosmic-ray.toml cosmic-ray.sqlite3
          uv run cr-report cosmic-ray.sqlite3
